### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [bfhcodehacker/bfh_splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by bfhcodehacker** [comment]
Thanks for the heads up. I added

  meta name="viewport" content="width=device-width, initial-scale=1"

to the head of application.html.erb  and 

@-ms-viewport{
  width: device-width;
}
 to master.css.scss. It looks much better on my phone now.

**Comment by MarcoMorawec** [comment]
:+1: 

Nice one @bfhcodehacker 

Make sure you close the issue, now that you fixed it :)
